### ISSUE TITLE
Porting themes to React95 🔥

### ISSUE THREAD

**Issue by arturbien** [tpenguinltg/winclassic#5]
Hey! I just noticed you're really into creating color themes for Windows 95/98.

I'm a creator and maintainer of [React95](https://react95.io/) and we implemented theming functionality and it would be awesome to use theme's you've created! We already have a bunch of themes, but we could always have more, right? You can preview our current themes on our [Storybook](https://storybook.react95.io/?path=/story/window--default) via "Themes" widget, or here in [this app](https://coins95.web.app/settings) under `Appearance` tab.

If you want to get involved in our project or give some ideas how to improve we would be really happy to have you on board. ♥️
 
Sorry for polluting your issues but I wanted to get in touch with you.

Have a nice day!

**Comment by tpenguinltg** [comment]
Hey, this is a pleasant surprise! I'd love for you to add my themes. I can add a couple of issues to the repo to make it easy to port Windows themes over and see if I can get started on it.

No worries about polluting the issues. It's too bad GitHub doesn't have a way to message users directly. I'll close this issue now since it's not a real issue, but feel free to continue discussion here if you want to say anything more.
