### ISSUE TITLE
Use fonts from 98.css

### ISSUE THREAD

**Issue by SMUsamaShah** [tpenguinltg/winclassic#9]
Thanks for making this tool. Fonts are off though and you can really use fonts from 98.css https://github.com/jdan/98.css
They will fit in perfectly.

**Comment by tpenguinltg** [comment]
Thanks, but the font, Tahoma, is correct for the Windows XP/Vista/7 variant of Windows Classic. The intention was not to emulate the 9x variant, but the fallback fonts are the correct ones for the 9x variant.

https://github.com/tpenguinltg/winclassic/blob/a63b9cfefe6523710f70b7e17aa886b285c58b1c/styles/themes/theme-template.scss#L46

I've opened #10 for custom font support since it was on my to-do list from the start, but I'm not actively developing it anymore.
